version: '3.9'

services:
  fastapi:
    build: .                     # Dockerfile을 기준으로 빌드
    container_name: fastapi_app
    ports:
      - "8000:8000"
    restart: always              # 컨테이너가 죽더라도 자동 재시작
    command: python -m uvicorn fastAPI:app --host 0.0.0.0 --port 8000
